app = "hvo-property-svc-olivia"
primary_region = "sjc"

[build]
  dockerfile = "services/property-svc/Dockerfile"

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
